### ISSUE TITLE
Updates to README.md

### ISSUE THREAD

**Issue by sandrinodimattia** [zamd/wsfedidp#2]
A few comments to improve the readme file:
- Mention the `config\settings.json` file here: https://github.com/zamd/wsfedidp#running--testing-idp
- Mention that you might want to enter the organization name when running through this: https://github.com/zamd/wsfedidp#generate-a-root-ca-certificate
- Mention that you need to enter **fabrikam.net** as subject in this CSR https://github.com/zamd/wsfedidp#cerficate-signing-request-csr
- Mention that you need to enter something like **Jon Smith** as subject in this CSR: https://github.com/zamd/wsfedidp#cerficate-signing-request-csr-1
- I had some issues adding the cert to root. This command was useful on Mac: sudo security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" "/Users/me/Desktop/FabrikamRootCA.cer"

**Comment by sandrinodm** [comment]
Also had some issues with the documented `openssl` commands on OSX. These commands did work for me:

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout FabrikamRootCA.key -out FabrikamRootCA.cer 
openssl genrsa -out fabrikam.net.key 2048
openssl req -new -key fabrikam.net.key -out fabrikam.net.csr
openssl x509 -req -in fabrikam.net.csr -CA FabrikamRootCA.cer -CAkey FabrikamRootCA.key -CAcreateserial  -out fabrikam.net.cer
openssl req -new -key jon.key -out jon.csr
openssl pkcs12 -export -out jon.pfx -inkey jon.key -in jon.cer -certfile FabrikamRootCA.cer
```

(especially had issues with `-extension`, `-sha256`, `-config`)

**Comment by zamd** [comment]
**regarding openssl command options**, there was weird problem with **dashes** ('-') in front of few options like **-config**, **-extensions** etc. Apparently I have added these characters on a windows machine and mac terminal wasn't treating them as dashes at all and was throwing 'invalid options'.
